# Site settings
email: speedspeeder1@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-118657683-1

# SEO settings
title: Speed's Spectrum
description: Writeups of Mayank Lunayach
url: "https://blog.mayankl.org"
twitter_username: mayank_lunayach
default_img: https://s3.envato.com/files/205262583/Light%20speed%20preview%20image.jpg

# Profile settings
name: Mayank Lunayach
profile_img: "/assets/images/me/1.jpg"
profile: Mayank Lunayach was born in Jaipur, India . Currently, he is doing major in Electrical Engineering from Indian Institute of Technology, Kanpur. He's an open source developer and an AI enthusiast. He's decent at playing Cricket and can watch any kind of sports and even follow it.
social:
  github: https://github.com/lunayach
  facebook: https://www.facebook.com/mayank.lunayach
  twitter: https://twitter.com/mayank_lunayach
  quora: https://www.quora.com/profile/Mayank-Lunayach-1
  linkedin: https://www.linkedin.com/in/lunayach-mayank/



# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/
kramdown:
  input: GFM
  syntax_highlighter: rouge
# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer, rouge]
highlighter: rouge