# Site settings
email: speedspeeder1@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-118657683-1

# SEO settings
title: Writeups of Mayank Lunayach
description: Sharing whatever interesting I do....
url: "https://blog.mayankl.org"
twitter_username: mayank_lunayach
default_img: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfAuhp2djVCR5qPapmmRVLLVBaqjrndrMDxuIWZIseKDD26JUF

# Profile settings
name: Mayank Lunayach
profile_img: "/assets/images/me/1.jpg"
profile: Mayank Lunayach is from Jaipur, India. Currently, He is doing major in Electrical Engineering from Indian Institute of Technology, Kanpur. He is an open-source developer and an AI enthusiast. He is decent at playing Cricket, Table Tennis and reading Fiction. He can watch any kind of sport and loves to follow it.
social:
  github: https://github.com/lunayach
  facebook: https://www.facebook.com/mayank.lunayach
  twitter: https://twitter.com/mayank_lunayach
  quora: https://www.quora.com/profile/Mayank-Lunayach-1
  linkedin: https://www.linkedin.com/in/lunayach-mayank/



# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/
kramdown:
  input: GFM
  syntax_highlighter: rouge
# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
highlighter: